"""add products and uploads

Revision ID: 141d9836e35c
Revises: bf0db0adfd51
Create Date: 2026-05-02 13:34:58.936252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141d9836e35c'
down_revision: Union[str, Sequence[str], None] = 'bf0db0adfd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('mood_tags', sa.JSON(), nullable=False),
    sa.Column('price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('is_resellable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_limited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=True),
    sa.Column('stock_remaining', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='published', nullable=False),
    sa.Column('happy_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('purchase_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('collection_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_products_author_id'), 'emotion_products', ['author_id'], unique=False)
    op.create_index(op.f('ix_emotion_products_created_at'), 'emotion_products', ['created_at'], unique=False)
    op.create_index(op.f('ix_emotion_products_id'), 'emotion_products', ['id'], unique=False)
    op.create_index(op.f('ix_emotion_products_product_type'), 'emotion_products', ['product_type'], unique=False)
    op.create_index(op.f('ix_emotion_products_status'), 'emotion_products', ['status'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['emotion_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_emotion_products_status'), table_name='emotion_products')
    op.drop_index(op.f('ix_emotion_products_product_type'), table_name='emotion_products')
    op.drop_index(op.f('ix_emotion_products_id'), table_name='emotion_products')
    op.drop_index(op.f('ix_emotion_products_created_at'), table_name='emotion_products')
    op.drop_index(op.f('ix_emotion_products_author_id'), table_name='emotion_products')
    op.drop_table('emotion_products')
    # ### end Alembic commands ###
