"""add purchases and interactions

Revision ID: 50f479a36c32
Revises: 141d9836e35c
Create Date: 2026-05-02 13:52:15.144585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f479a36c32'
down_revision: Union[str, Sequence[str], None] = '141d9836e35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['emotion_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_product_collections_user_id_product_id')
    )
    op.create_index(op.f('ix_product_collections_id'), 'product_collections', ['id'], unique=False)
    op.create_index(op.f('ix_product_collections_product_id'), 'product_collections', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_collections_user_id'), 'product_collections', ['user_id'], unique=False)
    op.create_table('product_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['emotion_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_comments_id'), 'product_comments', ['id'], unique=False)
    op.create_index(op.f('ix_product_comments_product_id'), 'product_comments', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_comments_user_id'), 'product_comments', ['user_id'], unique=False)
    op.create_table('product_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['emotion_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_product_likes_user_id_product_id')
    )
    op.create_index(op.f('ix_product_likes_id'), 'product_likes', ['id'], unique=False)
    op.create_index(op.f('ix_product_likes_product_id'), 'product_likes', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_likes_user_id'), 'product_likes', ['user_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['emotion_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'product_id', name='uq_purchases_buyer_id_product_id')
    )
    op.create_index(op.f('ix_purchases_buyer_id'), 'purchases', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_index(op.f('ix_purchases_product_id'), 'purchases', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchases_seller_id'), 'purchases', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_seller_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_product_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_buyer_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_product_likes_user_id'), table_name='product_likes')
    op.drop_index(op.f('ix_product_likes_product_id'), table_name='product_likes')
    op.drop_index(op.f('ix_product_likes_id'), table_name='product_likes')
    op.drop_table('product_likes')
    op.drop_index(op.f('ix_product_comments_user_id'), table_name='product_comments')
    op.drop_index(op.f('ix_product_comments_product_id'), table_name='product_comments')
    op.drop_index(op.f('ix_product_comments_id'), table_name='product_comments')
    op.drop_table('product_comments')
    op.drop_index(op.f('ix_product_collections_user_id'), table_name='product_collections')
    op.drop_index(op.f('ix_product_collections_product_id'), table_name='product_collections')
    op.drop_index(op.f('ix_product_collections_id'), table_name='product_collections')
    op.drop_table('product_collections')
    # ### end Alembic commands ###
